import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#082032',
  },
  gradientBg: {
    flex: 1,
  },
  screen: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    paddingTop: 30,
    gap: 16,
    paddingBottom: 36,
  },
  header: {
    marginTop: 8,
  },
  title: {
    color: '#f8fafc',
    fontSize: 28,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  subtitle: {
    color: '#dbeafe',
    marginTop: 4,
    fontSize: 14,
  },
  panel: {
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderRadius: 20,
    padding: 14,
    borderWidth: 1,
    borderColor: '#bfdbfe',
  },
  panelHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  panelTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#0f172a',
  },
  primaryBtn: {
    backgroundColor: '#0f766e',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  primaryBtnText: {
    color: '#f0fdfa',
    fontWeight: '700',
  },
  secondaryBtn: {
    backgroundColor: '#1d4ed8',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  secondaryBtnText: {
    color: '#eff6ff',
    fontWeight: '700',
    fontSize: 12,
  },
  emptyText: {
    color: '#334155',
    fontSize: 14,
    lineHeight: 20,
  },
  doctorCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    backgroundColor: '#f8fafc',
    padding: 12,
    gap: 10,
  },
  activeDoctorCard: {
    borderColor: '#0ea5e9',
    backgroundColor: '#e0f2fe',
  },
  doctorCardActions: {
    alignItems: 'flex-end',
    gap: 6,
  },
  doctorName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0f172a',
  },
  doctorMeta: {
    color: '#334155',
    fontSize: 12,
  },
  slideCount: {
    color: '#334155',
    fontSize: 12,
    fontWeight: '600',
  },
  deleteText: {
    color: '#be123c',
    fontWeight: '700',
  },
  separator: {
    height: 10,
  },
  selectedDoctorInfo: {
    color: '#334155',
    marginTop: 2,
    maxWidth: 170,
  },
  slidesList: {
    gap: 10,
  },
  slideCard: {
    flexDirection: 'row',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#bfdbfe',
    backgroundColor: '#f8fafc',
    overflow: 'hidden',
  },
  slideCardActive: {
    opacity: 0.86,
  },
  slideImage: {
    width: 94,
    height: 94,
    backgroundColor: '#e2e8f0',
  },
  slideCardContent: {
    flex: 1,
    padding: 10,
    justifyContent: 'space-between',
  },
  slideTitle: {
    color: '#0f172a',
    fontWeight: '800',
    fontSize: 16,
  },
  slideHint: {
    color: '#475569',
    fontSize: 12,
  },
  removeSlideButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#fee2e2',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  removeSlideText: {
    color: '#9f1239',
    fontWeight: '700',
    fontSize: 12,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.58)',
    justifyContent: 'center',
    padding: 16,
  },
  modalCard: {
    backgroundColor: '#ffffff',
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: '#dbeafe',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#0f172a',
    marginBottom: 12,
  },
  input: {
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 10,
    fontSize: 14,
    color: '#0f172a',
    backgroundColor: '#f8fafc',
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 4,
  },
  modalSecondaryBtn: {
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  modalSecondaryText: {
    color: '#334155',
    fontWeight: '700',
  },
  modalPrimaryBtn: {
    backgroundColor: '#0f766e',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  modalPrimaryText: {
    color: '#f0fdfa',
    fontWeight: '800',
  },
  searchInput: {
    borderWidth: 1,
    borderColor: '#bfdbfe',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 10,
    fontSize: 14,
    color: '#0f172a',
    backgroundColor: '#f8fafc',
  },
  actionButtonsGroup: {
    flexDirection: 'row',
    gap: 8,
  },
  slideshowBtn: {
    backgroundColor: '#dc2626',
  },
  slideshowContainer: {
    flex: 1,
    backgroundColor: '#000000',
    justifyContent: 'center',
    alignItems: 'stretch',
  },
  slidePage: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  slideshowImage: {
    width: '100%',
    height: '100%',
  },
  slideshowFooter: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0,0,0,0.6)',
    paddingHorizontal: 16,
    paddingVertical: 12,
    alignItems: 'center',
  },
  slideshowIndicatorText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 16,
  },
  swipeHintText: {
    color: '#a0aec0',
    fontSize: 12,
    marginTop: 4,
  },
  slideNoteInput: {
    marginTop: 10,
    width: '100%',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.5)',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: '#ffffff',
    backgroundColor: 'rgba(15, 23, 42, 0.55)',
    fontSize: 14,
  },
  slideshowCloseBtn: {
    position: 'absolute',
    top: 40,
    right: 20,
    zIndex: 999,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(220, 38, 38, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  slideshowCloseBtnText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 20,
  },
});
