import { StyleSheet } from 'react-native';

// Modern color palette - minimalist two-color design
const PRIMARY_COLOR = '#3b82f6'; // Modern blue for buttons
const SECONDARY_COLOR = '#60a5fa'; // Lighter blue for hover states
const WHITE = '#ffffff';
const LIGHT_BG = '#f9fafb'; // Very light gray for backgrounds
const DARK_TEXT = '#1f2937'; // Dark gray for primary text
const MID_TEXT = '#6b7280'; // Medium gray for secondary text
const LIGHT_GRAY = '#e5e7eb'; // Light gray for borders/separators
const ERROR_COLOR = '#ef4444'; // Soft red for delete actions

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: WHITE,
  },
  gradientBg: {
    flex: 1,
  },
  screen: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    paddingTop: 30,
    gap: 16,
    paddingBottom: 36,
  },
  header: {
    marginTop: 8,
  },
  title: {
    color: DARK_TEXT,
    fontSize: 28,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  subtitle: {
    color: MID_TEXT,
    marginTop: 4,
    fontSize: 14,
  },
  panel: {
    backgroundColor: WHITE,
    borderRadius: 16,
    padding: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
  },
  panelHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  panelTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: DARK_TEXT,
    letterSpacing: -0.3,
  },
  primaryBtn: {
    backgroundColor: PRIMARY_COLOR,
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 11,
    shadowColor: PRIMARY_COLOR,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 3,
  },
  primaryBtnText: {
    color: WHITE,
    fontWeight: '600',
    fontSize: 14,
  },
  secondaryBtn: {
    backgroundColor: LIGHT_BG,
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderWidth: 1,
    borderColor: LIGHT_GRAY,
  },
  secondaryBtnText: {
    color: DARK_TEXT,
    fontWeight: '600',
    fontSize: 14,
  },
  emptyText: {
    color: MID_TEXT,
    fontSize: 14,
    lineHeight: 20,
  },
  doctorCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 12,
    backgroundColor: WHITE,
    padding: 12,
    gap: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 2,
    elevation: 1,
    borderWidth: 1,
    borderColor: LIGHT_GRAY,
  },
  activeDoctorCard: {
    borderColor: PRIMARY_COLOR,
    backgroundColor: '#f0f9ff',
    borderWidth: 2,
  },
  doctorCardActions: {
    alignItems: 'flex-end',
    gap: 6,
  },
  doctorName: {
    fontSize: 15,
    fontWeight: '600',
    color: DARK_TEXT,
  },
  doctorMeta: {
    color: MID_TEXT,
    fontSize: 12,
  },
  slideCount: {
    color: MID_TEXT,
    fontSize: 12,
    fontWeight: '500',
  },
  deleteText: {
    color: ERROR_COLOR,
    fontWeight: '600',
    fontSize: 13,
  },
  separator: {
    height: 14,
  },
  selectedDoctorInfo: {
    color: MID_TEXT,
    marginTop: 2,
    maxWidth: 170,
    fontSize: 13,
  },
  slidesList: {
    gap: 10,
  },
  slideCard: {
    flexDirection: 'row',
    borderRadius: 12,
    backgroundColor: WHITE,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 2,
    elevation: 1,
    borderWidth: 1,
    borderColor: LIGHT_GRAY,
  },
  slideCardActive: {
    opacity: 0.9,
    borderColor: PRIMARY_COLOR,
  },
  slideImage: {
    width: 94,
    height: 94,
    backgroundColor: LIGHT_BG,
  },
  slideCardContent: {
    flex: 1,
    padding: 10,
    justifyContent: 'space-between',
  },
  slideTitle: {
    color: DARK_TEXT,
    fontWeight: '600',
    fontSize: 14,
  },
  slideHint: {
    color: MID_TEXT,
    fontSize: 12,
  },
  removeSlideButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#fee2e2',
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  removeSlideText: {
    color: ERROR_COLOR,
    fontWeight: '600',
    fontSize: 12,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'center',
    padding: 16,
  },
  modalCard: {
    backgroundColor: WHITE,
    borderRadius: 16,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: DARK_TEXT,
    marginBottom: 16,
    letterSpacing: -0.3,
  },
  input: {
    borderWidth: 1,
    borderColor: LIGHT_GRAY,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 11,
    marginBottom: 10,
    fontSize: 14,
    color: DARK_TEXT,
    backgroundColor: LIGHT_BG,
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 8,
  },
  modalSecondaryBtn: {
    borderWidth: 1,
    borderColor: LIGHT_GRAY,
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: LIGHT_BG,
  },
  modalSecondaryText: {
    color: DARK_TEXT,
    fontWeight: '600',
    fontSize: 14,
  },
  modalPrimaryBtn: {
    backgroundColor: PRIMARY_COLOR,
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    shadowColor: PRIMARY_COLOR,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 3,
  },
  modalPrimaryText: {
    color: WHITE,
    fontWeight: '600',
    fontSize: 14,
  },
  searchInput: {
    borderWidth: 1,
    borderColor: LIGHT_GRAY,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 11,
    marginBottom: 10,
    fontSize: 14,
    color: DARK_TEXT,
    backgroundColor: LIGHT_BG,
  },
  actionButtonsGroup: {
    flexDirection: 'row',
    gap: 8,
  },
  slideshowBtn: {
    backgroundColor: PRIMARY_COLOR,
  },
  slideshowContainer: {
    flex: 1,
    backgroundColor: '#000000',
    justifyContent: 'center',
    alignItems: 'stretch',
  },
  slidePage: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  slideshowImage: {
    width: '100%',
    height: '100%',
  },
  slideshowFooter: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0,0,0,0.6)',
    paddingHorizontal: 16,
    paddingVertical: 12,
    alignItems: 'center',
  },
  slideshowIndicatorText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 16,
  },
  swipeHintText: {
    color: '#a0aec0',
    fontSize: 12,
    marginTop: 4,
  },
  slideNoteInput: {
    marginTop: 10,
    width: '100%',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.5)',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: '#ffffff',
    backgroundColor: 'rgba(15, 23, 42, 0.55)',
    fontSize: 14,
  },
  slideshowCloseBtn: {
    position: 'absolute',
    top: 40,
    right: 20,
    zIndex: 999,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: PRIMARY_COLOR,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: PRIMARY_COLOR,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 4,
  },
  slideshowCloseBtnText: {
    color: WHITE,
    fontWeight: '700',
    fontSize: 20,
  },
  loaderContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loaderCard: {
    backgroundColor: WHITE,
    borderRadius: 16,
    paddingHorizontal: 30,
    paddingVertical: 24,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
  loaderText: {
    marginTop: 12,
    color: DARK_TEXT,
    fontSize: 14,
    fontWeight: '600',
  },
});
